### ISSUE TITLE
making docs hangs

### ISSUE THREAD

**Issue by Datseris** [tkf/Bifurcations.jl#1]
```
julia> cd(Pkg.dir("Bifurcations")*"/docs")

julia> include("make.jl")
Documenter: setting up build directory.
Documenter: expanding markdown templates.
```
hangs for me, on current master, Julia 0.6.2. It has been 20 minutes since I submitted the command but it hasn't progressed yet. Does it indeed take a very large amount of time, or could there be an issue?

**Comment by tkf** [comment]
Ooops, sorry for the late reply. Totally wasn't expecting any issues were coming to this repo.

Anyway, `time julia docs/make.jl` says it takes 1 min and 30 sec in my laptop.  Everything is build in Travis always so I think I've been keeping `docs/make.jl` healthy.  You can look at the GitHub pages http://tkf.github.io/Bifurcations.jl/latest if you just want to look at the docs, although there are almost no docs :)

**Comment by Datseris** [comment]
awesome, thanks! I thought there were no docs hosted online. Maybe link http://tkf.github.io/Bifurcations.jl/latest  in the readme? :)

**Comment by tkf** [comment]
Well, it's not ready for use so I wanted to hide it from Google :)  But yeah, I'll put a link at some point.
