### ISSUE TITLE
step size maximum

### ISSUE THREAD

**Issue by rveltz** [tkf/Bifurcations.jl#13]
Hi,

I am trying your package on a specific example and I would like to set a maximal step size in codim1 continuation.  Is `h0` the right option to do this?

Thank you for your help,

```julia
solver = init(prob, h0 = 0.001)
```

**Comment by tkf** [comment]
`h0` is the initial step size. There is `h_min` but no `h_min` at the moment. Probably not too difficult to add, though.

**Comment by rveltz** [comment]
Ah! Thank you. I managed to use your package, the issue was not about `h_max`...
